// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ProcessExcelFiles(arg1, arg2) {
  return window['go']['main']['App']['ProcessExcelFiles'](arg1, arg2);
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}
