// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolderDialog():Promise<string>;

export function ProcessExcelFiles(arg1:string,arg2:string):Promise<void>;

export function SelectOutputFolder():Promise<string>;
